version: '2'
services:
    jhipsterlunchmeeting-app:
        image: jhipsterlunchmeeting
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsterlunchmeeting-mysql:3306/jhipsterlunchmeeting?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8084:8084
    jhipsterlunchmeeting-mysql:
        extends:
            file: mysql.yml
            service: jhipsterlunchmeeting-mysql
